[package]
name = "enigo"
version = "0.0.2"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]
build = "build.rs"

description = "Enigo lets you control your mouse (and keyboard in the future) in an abstract way on different operating systems (currently only Linux – macOS, Win and Redox planned)"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/pythoneer/enigo"
readme = "README.md"
keywords = ["input", "mouse", "testing", "keyboard"]
categories = ["gui"]
license = "MIT"

[dependencies]
lazy_static = "0.2.0"
libc = "0.2"
x11-dl = "2.12.0"

[build-dependencies]
pkg-config = "0.3.8"
