[package]
name = "enigo"
version = "0.0.11"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]
build = "build.rs"

description = "Enigo lets you control your mouse and keyboard in an abstract way on different operating systems (currently only Linux, macOS, Win – Redox and *BSD planned)"
documentation = "https://docs.rs/enigo/"
homepage = "https://github.com/enigo-rs/enigo"
repository = "https://github.com/enigo-rs/enigo"
readme = "README.md"
keywords = ["input", "mouse", "testing", "keyboard", "automation"]
categories = ["development-tools::testing", "api-bindings", "hardware-support"]
license = "MIT"

[badges]
travis-ci = { repository = "enigo-rs/enigo" }
appveyor = { repository = "pythoneer/enigo-85xiy" }

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[features]
with_serde = ["serde", "serde_derive"]

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.12.4"
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.8"
