[package]
name = "enigo"
version = "0.0.5"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]
build = "build.rs"

description = "Enigo lets you control your mouse (and keyboard in the future) in an abstract way on different operating systems (currently only Linux, macOS, Win – and Redox planned)"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/pythoneer/enigo"
readme = "README.md"
keywords = ["input", "mouse", "testing", "keyboard"]
categories = ["development-tools::testing", "api-bindings", "hardware-support"]
license = "MIT"

[dependencies]
lazy_static = "0.2.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.6.0"
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
x11-dl = "2.12.0"
regex = "0.2"

[build-dependencies]
pkg-config = "0.3.8"
